# Generated by Django 5.1.5 on 2025-02-03 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='position',
        ),
    ]
