# Generated by Django 5.1.5 on 2025-02-03 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_remove_rating_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='description',
            field=models.TextField(default='no'),
        ),
    ]
